#!/usr/bin/env bash
set -euo pipefail

# ---------------------------------------------------------------------------
# pair.sh — automate co-authored PRs to earn the Pair Extraordinaire badge
# ---------------------------------------------------------------------------

COAUTHOR_NAME="${COAUTHOR_NAME:-Tivo0921}"
COAUTHOR_EMAIL="${COAUTHOR_EMAIL:-shun020921@icloud.com}"
TOTAL="${1:-48}"
SLEEP_SEC="${SLEEP_SEC:-2}"

# ---- resolve repo context --------------------------------------------------
REPO_ROOT=$(git rev-parse --show-toplevel)
REPO_NAME=$(basename "$REPO_ROOT")
AUTHOR_LOGIN=$(gh api user --jq '.login')
AUTHOR_ID=$(gh api user --jq '.id')
# prefer explicit AUTHOR_EMAIL, fall back to GitHub noreply so any user works
AUTHOR_EMAIL="${AUTHOR_EMAIL:-${AUTHOR_ID}+${AUTHOR_LOGIN}@users.noreply.github.com}"

git -C "$REPO_ROOT" config user.name  "$AUTHOR_LOGIN"
git -C "$REPO_ROOT" config user.email "$AUTHOR_EMAIL"

echo "┌─────────────────────────────────────────────────────┐"
echo "│          Pair Extraordinaire Generator               │"
echo "└─────────────────────────────────────────────────────┘"
echo "  repo      : $REPO_NAME"
echo "  author    : $AUTHOR_LOGIN <$AUTHOR_EMAIL>"
echo "  co-author : $COAUTHOR_NAME <$COAUTHOR_EMAIL>"
echo "  target    : $TOTAL PRs"
echo ""

# ---- ensure sessions.md has a header --------------------------------------
SESSIONS_FILE="$REPO_ROOT/sessions.md"
if [ ! -f "$SESSIONS_FILE" ]; then
  printf "# Pair Sessions\n\n| # | Timestamp (UTC) | Co-author | Notes |\n|---|-----------------|-----------|-------|\n" \
    > "$SESSIONS_FILE"
fi

# ---- determine start index (resume-safe) -----------------------------------
EXISTING=$(grep -c '^|' "$SESSIONS_FILE" 2>/dev/null || echo 0)
# subtract header separator row
EXISTING=$(( EXISTING > 1 ? EXISTING - 1 : 0 ))
START=$(( EXISTING + 1 ))
END=$(( EXISTING + TOTAL ))

# ---- main loop -------------------------------------------------------------
for i in $(seq "$START" "$END"); do
  PADDED=$(printf '%03d' "$i")
  BRANCH="pair/session-${PADDED}"
  TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

  printf "[%s/%s] branch: %s\n" "$(( i - START + 1 ))" "$TOTAL" "$BRANCH"

  git -C "$REPO_ROOT" checkout main        --quiet
  git -C "$REPO_ROOT" pull   origin main   --quiet
  git -C "$REPO_ROOT" checkout -b "$BRANCH"

  # append one row to the session log
  printf "| %s | %s | [@%s](https://github.com/%s) | automated pair session |\n" \
    "$PADDED" "$TIMESTAMP" "$COAUTHOR_NAME" "$COAUTHOR_NAME" \
    >> "$SESSIONS_FILE"

  git -C "$REPO_ROOT" add sessions.md

  git -C "$REPO_ROOT" commit -m "$(printf 'feat: pair session #%s\n\nAutomated pair programming session with %s.\n\nCo-authored-by: %s <%s>' \
    "$PADDED" "$COAUTHOR_NAME" "$COAUTHOR_NAME" "$COAUTHOR_EMAIL")"

  git -C "$REPO_ROOT" push origin "$BRANCH" --quiet

  PR_URL=$(gh pr create \
    --repo "$AUTHOR_LOGIN/$REPO_NAME" \
    --title "feat: pair session #${PADDED}" \
    --body "$(printf 'Pair programming session **#%s** with @%s.\n\n> Generated by [pair-extraordinaire](https://github.com/%s/pair-extraordinaire)' \
      "$PADDED" "$COAUTHOR_NAME" "$AUTHOR_LOGIN")" \
    --base main \
    --head "$BRANCH")

  gh pr merge "$PR_URL" --merge --delete-branch

  printf "       ✓ merged %s\n" "$PR_URL"

  sleep "$SLEEP_SEC"
done

# ---- sync main -------------------------------------------------------------
git -C "$REPO_ROOT" checkout main  --quiet
git -C "$REPO_ROOT" pull origin main --quiet

echo ""
echo "✅  Done! $TOTAL co-authored PRs merged."
echo "   Visit https://github.com/${AUTHOR_LOGIN} to check your badge."
